src/main.py
It was only checking for comments for _submissions that weren't in the replied to list_
=> Fix comment replies on replied submissions

README.md, src/main.py
- This shouldn't change previous behavior, but rather clean things up in preparation for further work
- It also adds a `--simulate` option, which will allow us to test out updating the posts_replied_to state without actually making reddit posts. This basically sets us up to add in Firestore and easily test it out.
=> Refactor and add simulate option

README.md, requirements-dev.txt, src/main.py, src/requirements.txt
Add Firestore integration (Closes #15)
I feel a little odd about it because the dev workflow requires passing in google credentials, even for the emulated version of firestore. I'm hopeful we can do better down the line.
I'd like to at least understand better whether this solution is at least portable. @Hucxley do the instructions in the readme work for you?
=> Firestore integration

README.md, requirements-dev.txt, src/main.py
`Black` is my favorite code formatter these days, because it doesn't require me (nor allow me) to spend any time thinking about the formatting of the code I'm writing, but instead just makes it all generally reasonable and compliant.
The top benefit is that if everyone on a project uses it consistently, there won't be any diffs in PRs that are purely formatting changes (extra newlines, single vs double quotes, etc..). Instead, every change you see is an actual code change, so you can focus on what's important. **I tend to hook things up in my IDE so that it auto-runs on save** along with `isort`.
[Black, the uncompromising code formatter](https://github.com/psf/black)
=> Blacken code

README.md, requirements-dev.txt, scripts/autoformat.sh, src/main.py, src/plan_bot.py, src/plan_bot_test.py, src/reddit_util.py, src/reddit_util_test.py
- Start moving business logic out of main.py and into other files
- Create wrapper classes for `Post` and `Submission` in order to provide a standard interface for overlapping functionality
- For example, `comment.body` vs `submission.selftext` is now `comment.text` and `submission.text`
- Begin adding tests for business logic and helper classes
- Restore proper behavior of `--skip-tracking`
=> Tests and reddit_util wrapper classes

planbot.tf, src/posts_replied_to.txt
We no longer use that file, and at this point the post list is out of date anyhow :)
=> Remove posts_replied_to.txt

src/plan_bot.py
- Set initialized confidence strength to 50, 
- if match_confidence < initial, log post.text and details about the failed match for review of plans db for improvement.
- Changed fuzzy match type to fuzz.token_sort_ratio since WRatio has been returning incorrect matches
has not been deployed
=> Set confidence threshold, log low confidence matches

src/plan_bot.py, src/plan_bot_test.py
Closes #24 
Work towards #23 
Addresses comments from #22
=> Improve info stored about posts

README.md, src/keyword-extractor.py, src/labeled_posts.json, src/main.py, src/matching.py, src/plan_bot.py, src/plans.json, src/score_strategies.py, src/synonym_keyphrase_candidates.json
- Move plan ids to be human readable strings
- Useful for labeling posts based on the desired plan match
- Matches how FireStore stores docs
- Remove the layer of nesting in `plans.json`
- All uses of it calling the `["plans"]` property anyway
- Matches how they'd eventually be stored in FireStore
- Move matching strategy to `matching.py`
- We can add new candidate strategies here without conflicting with any current working strategies
- Add `labeled_posts.json`
- Seeded with the plan topics we already had, as well as some obvious ones that came to mind
- Here is where we can add additional text that is scraped from or inspired by posts to /r/warren etc...
- Allows for the case
- Add scoring script to evaluate matching strategies
- Allows us to quickly compare the performance of different …
=> Test harness for strategies

README.md, src/plan_bot.py
@Hucxley we've gotta get you set up with a working dev environment!
post db entries now look like
```
{'post_parent_id': 'cmp4qa', 'plan_match': 'immigration_reform', 'top_plan': 'immigration_reform', 'reply_timestamp': DatetimeWithNanoseconds(2019, 8, 14, 13, 19, 18, 116000, tzinfo=<UTC>), 'post_text': '!WarrenPlanBot immigration reform', 'post_subreddit': '22n1sz', 'post_title': None, 'top_plan_confidence': 72, 'type': 'comment', 'post_author': '/u/WPB_dev_2', 'post_url': 'https://www.reddit.com/r/WPBSandbox/comments/cmp4qa/i_like_her_but_does_she_have_a_plan_for/ewl1no8/', 'post_top_level_parent_id': 'cmp4qa', 'replied': True}
```
=> Fix errors from #32

src/plan_bot.py, src/requirements.txt
- Added subreddit display name for human-readable form
- Added pprint to requirements for pretty printing
- Added "speedup" option to fuzzywuzzy import to include python-levenshtein in the package
- Moved DRY posts_db construction to function
- Moved business logic for metadata extraction into post_db entry construction
=> Cleanup and Refactoring

src/plan_bot.py, src/requirements.txt
It isn't needed.  Also, I may have (probably, most likely) messed up these last 2 PRs
=> Remove pprint

src/plans.json
- Added new plan info for Tribal Natiohns and Indigenous Peopls plan.
=> Update plans file

src/plans.json
- Fix typo
- Remove more first person language
=> Cleanup plans json

Dockerfile, README.md, docker-compose.yml
We won't be able to hit that emulated firestore until https://github.com/joegoldbeck/wpb-bot/issues/58 is done though
=> Add cloud client and Firestore emulator to container

scripts/keyword_extractor.py
- Added more text preprocessing
- Lowered score threshold from 10.0 to 7.0
- Raised max words per keyphrase to 4
- Writes output to JSON file in data/keyphrases/ in "keyphrase":score format
=> Enhancements to auto keyword extractor

src/matching.py, src/plan_bot.py, src/plan_bot_test.py
- stuff to make that stuff work
=> added all the plans request

src/matching.py
=> Suppress gensim logs

src/main.py
This way, the response time will be less than a minute!
We run the cloud function once a minute, but then plan bot will run in a loop for 40 seconds responding to any new posts it sees. There will then be 20 seconds of buffer, in case the bot is running slow for some reason (currently each iteration through the loop takes ~2 secs) 
Tested this out on WPBSandbox, and it's a _much_ better UX. I sent a comment and got a reply within a few seconds :D
=> Run plan bot in a loop on gcp

scripts/labeled_posts.json
--Top Strategies--
lsa_gensim_v2: TOTAL SCORE: 95.45454545454545
tfidf_gensim_v2: TOTAL SCORE: 82.57575757575758
token_sort_lsi_v1_composite: TOTAL SCORE: 72.72727272727273
lsi_gensim_v1: TOTAL SCORE: 57.57575757575758
token_sort_ratio: TOTAL SCORE: 53.03030303030303
=> Add more labeled posts from /r/elizabethwarren

src/main.py
This might get kind of long by the end of the day
=> Remove log of all posts previously processed

scripts/labeled_posts.json, src/matching.py, src/matching_test.py
Closes #123 
This seems to fit with how people are using the bot in practice, and will make the UX better as a result :)
=> Trigger line

src/plans.json
Relates to #130 
Even though this doesn't have any more details than the original, it seems like a stronger prompt to get people to click through to the plan itself
=> Use tagline from ewarren for trade summary

src/plan_bot.py, src/plan_bot_test.py
=> Simplify footer

src/plan_bot.py
Turns out we say this one pretty often, and most of the time our guesses are pretty good! This makes it seem less like we're just guessing, and more like we know we're doing something useful, which like 90% of the time we are!
=> Change tone of "I'm not sure" response

src/plans.json
=> Replace summaries with the call-to-action text on the website

src/main.py, src/plan_bot.py
Initial logging update here.   I did a little extra work to allow us to have a "debug" log level that doesn't also barf debug logging from other imported modules (like `prawcore` and `urllib3`) at us.   This was mostly to scratch my own itch of wanting a "debug" level that will print reply responses, without having to have them present in the output at all times.  It could maybe be useful for other things, too.  The levels on all of this are totally open to adjustment.
I only tackled the actual core program logic here, not any of the utility scripts.   I can adapt those as well if we think it would be useful, or we can just merge this and flag that as a to-do for later if folks want it.  I'm fine either way!
=> added logging to main and plan_bot
